##############################################
################## LOCAL ####################
##############################################
POST http://localhost:3000/api/v1/bookings/new-booking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbE5hbWUiOiJKb2huIERvZSIsImZhbWlseU5hbWUiOiJEb2UiLCJwaG9uZU51bWJlciI6Iis2MjEyMzQ1Njc4OTAiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWRlbnRpdHlUeXBlIjoiUGFzc3BvcnQiLCJpZGVudGl0eU51bWJlciI6IkExMjM0NTY3OCIsIm5hdGlvbmFsaXR5IjoiSW5kb25lc2lhbiIsImVtYWlsSXNWZXJpZmllZCI6dHJ1ZSwiZ29vZ2xlSWQiOm51bGwsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE3ODIzODMxfQ.9n4_nC6bmuMCscYyFLypihULNm5ePSDYLUS0uoebAqA

{
    "userId": 2,
    "flightId": 160,
    "adult": 2,
    "child": 0,
    "baby": 1,
    "seatClass": "Business",
    "passenger": [
        {
            "title": "Mr",
            "fullName": "By",
            "familyName": "Ewok",
            "birthDate": "1980-01-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "123456123",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "ADULT"
        },
        {
            "title": "Mrs",
            "fullName": "Mega",
            "familyName": "Maharani",
            "birthDate": "1985-02-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "987654123",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "ADULT"
        },
        {
            "title": "Baby",
            "fullName": "Iwan",
            "familyName": "Aja",
            "birthDate": "2024-01-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "000000000",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "BABY"
        }
    ]
}


### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "emailOrPhoneNumber": "john@gmail.com",
    "password": "123456"
}

### GET ALL 
GET https://web-app-backend-git-development-aviaticks-projects.vercel.app/api/v1/bookings/booking-history
=======
### GET ALL BOOKING HISTORY 
GET http://localhost:3000/api/v1/bookings/booking-history


### GET BOOKING BY BOOKING CODE
GET http://localhost:3000/api/v1/bookings/booking-history?search=d

### GET BOOKING BY BOOKING ID
GET http://localhost:3000/api/v1/bookings/booking-history/2

### GET BOOKING BY CREATED AT BOOKING
GET http://localhost:3000/api/v1/bookings/booking-history?date=2024-06-03

### REGISTER USER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "fullName": "Abiyi Aja",
    "email": "21082010203@student.upnjatim.ac.id",
    "phoneNumber": "082123468464",
    "password": "123456"
}

### VERIFY OTP
POST http://localhost:3000/api/v1/auth/verify-otp
Content-Type: application/json

{
    "email": "21082010208@student.upnjatim.ac.id",
    "otp": "233629"
}

### RESEND OTP
POST http://localhost:3000/api/v1/auth/resend-otp
Content-Type: application/json

{
    "email": "21082010203@student.upnjatim.ac.id"
}

### LOGIN USER
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "emailOrPhoneNumber": "john@gmail.com",
    "password": "123456"
}

### VERIFIED USER CHECK
GET http://localhost:3000/api/v1/auth/verified
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbE5hbWUiOiJKb2huIERvZSIsImZhbWlseU5hbWUiOiJEb2UiLCJwaG9uZU51bWJlciI6Iis2MjEyMzQ1Njc4OTAiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWRlbnRpdHlUeXBlIjoiUGFzc3BvcnQiLCJpZGVudGl0eU51bWJlciI6IkExMjM0NTY3OCIsIm5hdGlvbmFsaXR5IjoiSW5kb25lc2lhbiIsImVtYWlsSXNWZXJpZmllZCI6dHJ1ZSwiZ29vZ2xlSWQiOm51bGwsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzE3ODIzODMxfQ.9n4_nC6bmuMCscYyFLypihULNm5ePSDYLUS0uoebAqA

### DELETE USER
DELETE  http://localhost:3000/api/v1/auth/users/32

### POST PROMO
POST http://localhost:3000/api/v1/promos
Content-Type: application/json

{
    "name": "Promo 22222 Aviatick",
    "discount": 0.12,
    "validFrom": "2024-06-01 00:00:00",
    "validUntil": "2024-06-07 20:54:00"
}

### POST NOTIFICATION
POST http://localhost:3000/api/v1/notifications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZnVsbE5hbWUiOiJDaGFybGllIERhdmlzIiwiZmFtaWx5TmFtZSI6IkRhdmlzIiwicGhvbmVOdW1iZXIiOiIrNjIxMjM0NTY3ODk0IiwiZW1haWwiOiJjaGFybGllQGdtYWlsLmNvbSIsImlkZW50aXR5VHlwZSI6IlBhc3Nwb3J0IiwiaWRlbnRpdHlOdW1iZXIiOiJCMjM0NTY3ODkiLCJuYXRpb25hbGl0eSI6IkluZG9uZXNpYW4iLCJlbWFpbElzVmVyaWZpZWQiOnRydWUsImdvb2dsZUlkIjpudWxsLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTc3Njg3MDl9.CuHeh6ht_daFmdPimc5ais2J6okUunlCJQPDYxMpgHY

{
    "title": "Pesawat Tempur xxx",
    "message": "Poke"
}

### UPDATE TICKET WITH PROMO
PUT http://localhost:3000/api/v1/promos/6
Content-Type: application/json

{
    "promoId": 4
}

###
PUT http://localhost:3000/api/v1/promos/update-status

### GET ALL PROMO
GET http://localhost:3000/api/v1/promos

##############################################
################## DEPLOY ####################
##############################################



### CREATE BOOKING
POST https://web-app-backend-git-development-aviaticks-projects.vercel.app/api/v1/bookings/new-booking
Content-Type: application/json

{
    "userId": 2,
    "flightId": 1,
    "adult": 2,
    "child": 0,
    "baby": 1,
    "seatClass": "Economy",
    "passenger": [
        {
            "title": "Mr",
            "fullName": "Kibow",
            "familyName": "Ewok",
            "birthDate": "1980-01-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "123456123",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "ADULT"
        },
        {
            "title": "Mrs",
            "fullName": "Puan",
            "familyName": "Maharani",
            "birthDate": "1985-02-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "987654123",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "ADULT"
        },
        {
            "title": "Baby",
            "fullName": "Iwan",
            "familyName": "Aja",
            "birthDate": "2024-01-01T00:00:00.000Z",
            "nationality": "Indonesia",
            "identityType": "KTP",
            "issuingCountry": "Indonesia",
            "identityNumber": "000000000",
            "expiredDate": "2025-01-01T00:00:00.000Z",
            "ageGroup": "BABY"
        }
    ]
}

### GET ALL 
GET https://web-app-backend-git-development-aviaticks-projects.vercel.app/api/v1/bookings/booking-history

### GET DETAIL 
GET https://web-app-backend-git-development-aviaticks-projects.vercel.app/api/v1/bookings/booking-history/3


